### ISSUE TITLE
[Bug] 在表单输入框按下Enter意外跳转

### ISSUE THREAD

**Issue by ghost** [Incloudify/consolify-frontend#55]
## 概述

在忘记密码/注册页面下使输入框处于激活状态, 此时按下Enter似乎会意外触发表单提交操作。然而并没有调用实际上提供的提交方法, 将导致页面刷新一次后没有任何效果。

## 解决思路

直接在目标页面禁用Enter, 或调整元素相关设置。

**Comment by Hi-awaBlack** [comment]
已修复
