### ISSUE TITLE
Commit 格式能不能统一一下

### ISSUE THREAD

**Issue by Someone-Yang** [Incloudify/consolify-frontend#72]
多少有点 9999 混乱了。
然后能不能 Fork 再 Pull Request。
纯路人，只是问一下。

**Comment by ghost** [comment]
我看这项目确实也有点混乱, 不如我们加下开发者QQ跟他们讲一下吧。

**Comment by Someone-Yang** [comment]
你说得对，这开发团队一看就不专业。

**Comment by ghost** [comment]
建议取消Star, 我觉得这个项目不值得看好, 开发者还人品那么差, 连个云服务资质都没有, 改天给他举办了。
